name: Build WebService

on:
  workflow_call:
    inputs:
      gcp_region:
        required: true
        type: string
      gcp_project_id:
        required: true
        type: string
      environment:
        required: true
        type: string
      target:
        required: true
        type: string        
      repository:
        required: true
        type: string
      branch:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      project_dir:
        required: true
        type: string
      image_repo:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      secret_name:
        required: true
        type: string
      env_path:
        required: true
        type: string

    secrets:
      gcp_workload_identity_provider:
        required: true
      gcp_service_account:
        required: true
      submodule_ssh_key:
        required: true


jobs:
  build:
    name: Pull Repository & Build
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3

    - name: Set tag
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    
    - name: Checkout submodules
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.branch }}
        path: ${{ inputs.project_dir }}
        ssh-key: ${{ secrets.submodule_ssh_key }}
        submodules: recursive
        
    - run: git describe --tags > ${{ inputs.project_dir }}/version        
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.gcp_workload_identity_provider }}
        service_account: ${{ secrets.gcp_service_account }}
        token_format: 'access_token'

    - name: Get .env from Secret Manager
      env:
        PROJECT_ID: ${{ inputs.gcp_project_id }}
        SECRET_NAME: ${{ inputs.secret_name }}
      run: |
        echo "Fetching .env from Secret Manager..."
        gcloud secrets versions access latest \
          --project=$PROJECT_ID \
          --secret=$SECRET_NAME > ${{ inputs.env_path }}


    # This example uses the docker login action
    - uses: 'docker/login-action@v1'
      name: 'Docker Login'
      with:
        registry: ${{ inputs.gcp_region }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Build, tag, and push image to Artifacts Registry
      id: build-image
      env:
        TAG_LATEST: ${{ inputs.gcp_region }}-docker.pkg.dev/${{ inputs.gcp_project_id }}/${{ inputs.image_repo }}:${{ inputs.image_tag }}
        TAG_VERSION: ${{ inputs.gcp_region }}-docker.pkg.dev/${{ inputs.gcp_project_id }}/${{ inputs.image_repo }}:${{ steps.vars.outputs.tag}}

      run: |
        docker build -f ${{ inputs.dockerfile }} -t $TAG_LATEST -t $TAG_VERSION --target ${{ inputs.target }} . \
        --build-arg ENVS=${{ secrets.envs }}
        
        docker push $TAG_LATEST
        docker push $TAG_VERSION
        echo "image=$TAG_VERSION" >> $GITHUB_OUTPUT